export const sperky = [
  {
    cislo_fotky: "0017",
    typ:["brož","spona na oděv"],
    material:[ "chirurgická ocel","drahé kameny"],
    technika:[ "kované","tepané"],
    opracovani:["leštěné"],
    lokalita: ["české"],
    kamen:[ "železitý křemen","olivín"],
    motiv: ["zoomorfní"],
    kolekce: ["Země česká"], 
    nazev: "kočka",
  },
  {
    cislo_fotky: "0018",
    typ: ["náramek"],
    material: ["chirurgická ocel","drahé kameny"],
    technika: ["kované","tepané"],
    opracovani: ["výbrusy"],
    lokalita: ["zahraniční"],
    kamen: ["křišťál","modrý křemen"],
    motiv: ["abstraktní a jiné"],
    kolekce: ["Země česká"],
    nazev: "blankytně",
  },
  {
   cislo_fotky:"0027",
   typ:["náhrdelník"],
   material:["chirurgická ocel","drahé kameny"],
   technika:["kované", "tepané"],
   opracovani: ["leštěné"],
   lokalita:["zahraniční"],
   kamen:["achát","karneol"],
   motiv:["abstraktní a jiné"],
   kolekce:[""],
   nazev: "divoch",
  },
  {
    cislo_fotky:"0149",
    typ:["souprava"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita:["zahraniční"],
    kamen:["australský drahý opál"],
    motiv:["abstraktní a jiné"],
    kolekce:[""],
    nazev: "opálovost",
   },
   {
    cislo_fotky:"0150",
    typ:["souprava"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["výbrusy"],
    lokalita:["zahraniční"],
    kamen:["jaspis","picasso jaspis"],
    motiv:["abstraktní a jiné"],
    kolekce:[""],
    nazev: "picasso",
   },
   {
    cislo_fotky:"0038",
    typ:["brož","spona na oděv"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita:["zahraniční"],
    kamen:["tyrkenit"],
    motiv:["zoomorfní"],
    kolekce:[""],
    nazev: "tyrkenitový motýl",
   },
   {
    cislo_fotky:"0048",
    typ:["nahrdelnik"],
    material:["chirurgická ocel","fosílie"],
    technika:["kované", "tepané"],
    opracovani: ["surové"],
    lokalita:["české","zahraniční"],
    kamen:["fosilie","granát"],
    motiv:["zoomorfní"],
    kolekce:["Marokem"],
    nazev: "šnekoid",
   },
   {
    cislo_fotky:"0030",
    typ:["náramek"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["surové"],
    lokalita:["zahraniční"],
    kamen:["perla"],
    motiv:["abstraktní a jiné"],
    kolekce:[""],
    nazev: "perlový náramek",
   },
   {
    cislo_fotky:"0036",
    typ:["naušnice"],
    material:["chirurgická ocel","skleněné"],
    technika:["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita:["zahraniční"],
    kamen:[""],
    motiv:[""],
    kolekce:["kousek Islandu"],
    nazev: "sea glass",
   },
   {
    cislo_fotky:"0157",
    typ:["přívěšek"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["wire-wrapping"],
    opracovani: ["výbrusy"],
    lokalita:["zahraniční"],
    kamen:["rubín"],
    motiv:["srdce"],
    kolekce:[""],
    nazev: "srdce s asterickým rubínem",
   },
   {
    cislo_fotky:"0130",
    typ:["naušnice"],
    material:["měď","(ne)obyčejné oblázky"],
    technika:["kované", "tepané"],
    opracovani: ["surové"],
    lokalita:["zahraniční"],
    kamen:["surová láva"],
    motiv:["abstraktní a jiné"],
    kolekce:["Kousek Islandu"],
    nazev: "bárky z ohně",
   },
   {
    cislo_fotky:"0363",
    typ:["přívěšek"],
    material:["zlato","sdrehé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita:["zahraniční"],
    kamen:[""],
    motiv:["heraldické znamení"],
    kolekce:["Z dávných dob"],
    nazev: "odřivous",
   },
   {
    cislo_fotky:"0093",
    typ:["stříbro"],
    material:["stříbro","drahé kameny"],
    technika:["klenotnická technika"],
    opracovani: ["výbrusy"],
    lokalita:["zahraniční"],
    kamen:["kubický zirkon"],
    motiv:["abstraktní a jiné"],
    kolekce:[""],
    nazev: "vesmír",
   },
   {
    cislo_fotky:"0284",
    typ:["naušnice"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["surové","leštěné"],
    lokalita:["české"],
    kamen:["vltavín, křišťál"],
    motiv:["abstraktní a jiné"],
    kolekce:["Země Česká"],
    nazev: "nechranická růže",
   },
   {
    cislo_fotky:"0332",
    typ:["přívěšek"],
    material:["chirurgická ocel","skleněné"],
    technika:["kované", "tepané"],
    opracovani: ["surové","leštěné"],
    lokalita:["české","zahraniční"],
    kamen:["vltavín","jaspis"],
    motiv:["křížek"],
    kolekce:["Země Česká"],
    nazev: "křížek s vltavínem",
   },
   {
    cislo_fotky:"0049",
    typ:["náhrdelník"],
    material:["chirurgická ocel","fosílie"],
    technika:["kované", "tepané"],
    opracovani: ["surové"],
    lokalita:["zahraniční"],
    kamen:["fosilie"],
    motiv:["zoomorfní"],
    kolekce:["Marokem"],
    nazev: "šnekoid ii",
   },
   {
    cislo_fotky:"0043",
    typ:["přívěšek"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["surové"],
    lokalita:["zahraniční","české"],
    kamen:["křišťál"],
    motiv:["antropomorfní"],
    kolekce:["Marokem", "Strážci a andělé"],
    nazev: "křišťálový strážce",
   },
   {
    cislo_fotky:"0160",
    typ:["náhrdelník"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita:["zahraniční"],
    kamen:["perleť","křišťál","granát"],
    motiv:["zoomorfní"],
    kolekce:["Okřídlení"],
    nazev: "perleťový motýl",
   },
   {
    cislo_fotky:"0137",
    typ:["brož","spona na oděv"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita:["zahraniční","české"],
    kamen:["achát"],
    motiv:["zoomorfní"],
    kolekce:["Okřídlení"],
    nazev: "brož s ptáčkem",
   },
   {
    cislo_fotky:"0064",
    typ:["náhrdelník"],
    material:["chirurgická ocel","drahé kameny"],
    technika:["kované", "tepané"],
    opracovani: ["leštěné"],
    lokalita:["české"],
    kamen:["achát"],
    motiv:["antropomorfní"],
    kolekce:["Stážci a andělé"],
    nazev: "bytost",
   },

];														
 																						
